version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-net-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
  dotnet-api:
    build: .
    container_name: dotnet-api
    ports:
      - "5280:5280"
      - "5005:5005"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql-net-db;Database=testdb;User=user;Password=password;"
    depends_on:
      - mysql-db